
#ifndef __LORConstants_h
#define __LORConstants_h

// Standard includes
#include <string>
#include <sstream>
#include <vector>
#include <cmath>

#include "vtkSlicerLinearObjectRegistrationModuleUtilitiesExport.h"

namespace LORConstants
{

  // Note: Do not remove any VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_MRML_EXPORT - it exports these functions so they are usable by the logic
  // Also note: The "extern" qualifier is required so we can define the constants in the cxx

  // This is for converting a position buffer to linear objects
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int REFERENCE_DOF;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int POINT_DOF;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int LINE_DOF;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int PLANE_DOF;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int UNKNOWN_DOF;

  // This is for the linear object types only
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string REFERENCE_STRING;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string POINT_STRING;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string LINE_STRING;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string PLANE_STRING;

  // This is for the spinner in the collection widget
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int REFERENCE_SPINNER_INDEX;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int POINT_SPINNER_INDEX;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int LINE_SPINNER_INDEX;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int PLANE_SPINNER_INDEX;

  // These are the collect states
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string REFERENCE_COLLECT_STATE;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string POINT_COLLECT_STATE;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string LINE_COLLECT_STATE;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string PLANE_COLLECT_STATE;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string UNKNOWNDOF_COLLECT_STATE;

  // These are the collect modes
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string MANUAL_DOF_COLLECT_MODE;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string MANUAL_SEGMENTATION_COLLECT_MODE;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string AUTOMATIC_COLLECT_MODE;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string MODEL_COLLECT_MODE;

  // These are constants values for the algorithm
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const double DIRECTION_SCALE;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const double ROTATION_THRESHOLD;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const double TRANSLATION_THRESHOLD;

  // Conversion functions
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT int COLLECT_STATE_TO_DOF( std::string s );
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT std::string DOF_TO_COLLECT_STATE( int d );
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT int DOF_TO_SPINNER_INDEX( int d );
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT int SPINNER_INDEX_TO_DOF( int i );
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT int STRING_TO_SPINNER_INDEX( std::string s );
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT std::string SPINNER_INDEX_TO_STRING( int i );
}

#endif