
#ifndef __LORConstants_h
#define __LORConstants_h

// Standard includes
#include <string>
#include <sstream>
#include <vector>
#include <cmath>

#include "vtkSlicerLinearObjectRegistrationModuleUtilitiesExport.h"

namespace LORConstants
{

  // Note: Do not remove any VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_MRML_EXPORT - it exports these functions so they are usable by the logic
  // Also note: The "extern" qualifier is required so we can define the constants in the cxx
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int REFERENCE_DOF;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int POINT_DOF;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int LINE_DOF;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int PLANE_DOF;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int UNKNOWN_DOF;

  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int REFERENCE_INDEX;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int POINT_INDEX;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int LINE_INDEX;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const int PLANE_INDEX;

  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string REFERENCE_STRING;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string POINT_STRING;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string LINE_STRING;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string PLANE_STRING;

  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string COLLECT_STRING;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string MANUAL_DOF_STRING;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string MANUAL_SEGMENTATION_STRING;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string AUTOMATIC_STRING;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const std::string MODEL_STRING;

  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const double DIRECTION_SCALE;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const double ROTATION_THRESHOLD;
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT extern const double TRANSLATION_THRESHOLD;

  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT int STRING_TO_DOF( std::string s );
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT std::string DOF_TO_STRING( int d );
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT int STRING_TO_INDEX( std::string s );
  VTK_SLICER_LINEAROBJECTREGISTRATION_MODULE_UTILITIES_EXPORT std::string INDEX_TO_STRING( int i );
}

#endif